sdbf:03:131:fdf75127393924a30ce4a480ad524bd09ada956795d5150942bb779ceda6ddc2/usr/lib/python3.4/site-packages/pip/_vendor/requests/exceptions.py:2517:sha1:256:5:7ff:160:1:42:AACoAQKECCAAEFAAAAAAQQAEAgAQAAYBAAAwAAEAICAAAAAAAAAAhAQwCAAAwAAERGAgACIIAEAEASAAABAAAACAAAAAAAEAAAAQATAAKAQAABAAEQABDCAAFAABAAAQAACIAAAQAACAQABAIFQAAgCAQACAAIgBEQAEBABwNYEEgACgGBAAAACAAAggAAAEQQIBGACCBCQAQAAgCIgCAQBAIBAAAAAAAAQAAAABABMAIgBAAACAAgQAQAVAAQYgAAIAUQBAJAECEDAAEAUIQAAABAACAAAFQCIAIgABJAAQAAgCIAwQgAAIQAAgQCAABAAAAACIBAAAkQAAAAQAEQ==
